# Generated by Django 4.2.14 on 2024-07-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='bike_model',
            field=models.CharField(default=True, help_text='укажите модель велосипеда', max_length=50, unique=True, verbose_name='модель велосипеда'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bike',
            name='is_rented',
            field=models.BooleanField(default=False, help_text='укажите статус аренды', verbose_name='статус аренды (арендован)'),
        ),
    ]
